import fs from "node:fs";
import path from "node:path";
import type {
  AnomaliesFile,
  AreasFile,
  CrosswalkFile,
  MarketNote,
  PriceBandsFile,
  ProjectsFile,
  QualityFile,
  RentBenchmarksFile,
  Summary,
} from "./types";

// Server-side loader. Files are generated by the Python pipeline into web/public/data and committed,
// so pages are rendered statically at build time (Vercel rebuilds on every data commit).
function load<T>(name: string): T {
  const file = path.join(process.cwd(), "public", "data", name);
  return JSON.parse(fs.readFileSync(file, "utf8")) as T;
}

export const getSummary = () => load<Summary>("summary.json");
export const getAreas = () => load<AreasFile>("areas.json");
export const getPriceBands = () => load<PriceBandsFile>("price_bands.json");
export const getRentBenchmarks = () => load<RentBenchmarksFile>("rent_benchmarks.json");
export const getAnomalies = () => load<AnomaliesFile>("anomalies.json");
export const getProjects = () => load<ProjectsFile>("projects.json");
export const getMarketNote = (): MarketNote | null => {
  try {
    return load<MarketNote>("market_note.json");
  } catch {
    return null;
  }
};
export const getQuality = (): QualityFile | null => {
  try {
    return load<QualityFile>("quality.json");
  } catch {
    return null;
  }
};
export const getCrosswalk = (): CrosswalkFile | null => {
  try {
    return load<CrosswalkFile>("crosswalk.json");
  } catch {
    return null;
  }
};
